# Generated by Django 5.0.1 on 2024-01-06 21:12

import game.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, validators=[game.validators.validate_username])),
                ('password', models.CharField(max_length=50, validators=[game.validators.validate_password])),
                ('rank', models.CharField(choices=[('N', 'Noob'), ('I', 'Intermediate'), ('P', 'Pro'), ('K', 'King')], default='N', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.IntegerField(validators=[game.validators.validate_age])),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=9, validators=[game.validators.validate_score])),
            ],
        ),
    ]
