<Kvbl>:

    rows:6
    cols: 6


    Button:
        text: "Hello 1"

    Button:
        text: "Hello 2"

    Button:
        text: "Hello 3"

    Button:
        text: "Hello 4"
        
    Button:
        text: "Hello 1"

    Button:
        text: "Hello 2"

    Button:
        text: "Hello 3"

    Button:
        text: "Hello 4"

    Button:
        text: "Hello 1"

    Button:
        text: "Hello 2"

    Button:
        text: "Hello 3"

    Button:
        text: "Hello 4"
