# Generated by Django 5.0.1 on 2024-01-08 20:55

import django.db.models.deletion
import tweet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, validators=[tweet.models.validate_username])),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('disliked_users', models.ManyToManyField(related_name='disliked_posts', to='tweet.user')),
                ('liked_users', models.ManyToManyField(related_name='liked_posts', to='tweet.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tweet.user')),
            ],
        ),
    ]
