# Generated by Django 5.0.1 on 2024-01-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to='tweet.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='outgoing_follow_requests',
            field=models.ManyToManyField(blank=True, related_name='incoming_follow_requests', to='tweet.user'),
        ),
    ]
